### Site info:
title: Записки безумного программиста
tagline: Программировать, программировать и еще раз программировать, как завещал великий...
author: Алекс О
email: bushmelev@gmail.com
description: "Блог безумного программиста в статике" # You can edit this line in _config.yml. It will appear in your document head meta and in your feed.xml site description
keywords: "Jekyll, программирование"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://oalex.appplantation.com" # the base hostname & protocol for your site
locale: "ru"

### Personal info and site tools info:
twitter_username: bushmelev
github_username:  abushmelev
disqus_shortname: oalex
favicon:     "/images/favicon.ico"
aboutme: Привет, меня зовут Алекс О. В меру упитанный, в самом расцвете сил. Я программист. Программирую на работе, на лево, по дороге в метро, в перерывах между всем этим. Мое хобби - программирование. Пробовал разводить кактусы - засохли.  # these are shown on aboutme-sidebar.
aboutme_photo: /images/oalex.png # my photo.
google_analytics_key: UA-20517923-5 # put YOUR key here to enable tracking! (blank to disable)

### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown where ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "ru" # blog sidebar language set, only include: English(en) and Chinese (cn)

locales:
    ru:
      Aboutme: "Обо мне"
      Archives: "Архивы"
      Blogroll: "Записки"        
      Categories: "Категории"    
      Copyright_Notice: "Авторские права"
      Recent_Posts: "Последние записи"
      Tags: "Теги" 
      Previous: "Обратно"
      Next: "Туда"
      PostedInCategories: "Отправлено в"   
      Taggedwith: "| таггед"
      PostDate: "| записано: "
      Google_search: "поиск"
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"
      PostDate: "on "
      Google_search: "Site Search"
### your Blogroll info, only name can shown on the page.

Blogroll:
      - name:  Алекс О
        href: http://bushmelev.ru/
        title: Миры Бушмелевых
      - name: author's website
        href: http://appplantation.com/
        title: App Plantation


### Build settings
markdown: kramdown
highlighter: pygments
paginate: 5
excerpt_separator: <!-- more -->
